global:
  namespace: &global-namespace gotk-system
  datadog:
    enabled: true
    url: &datadog-url ad.datadoghq.com
  
  extraPodAnnotations: {}

  prometheusAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

  env:
    httpsProxy:
    noProxy: 10.0.0.0/8,172.0.0.0/8

kraan:
  namespace: *global-namespace
  crd:
    enabled: true
  rbac:
    enabled: true
  netpolicy:
    enabled: true
  controller:
    enabled: true

    name: kraan-controller
    datadog:
      enabled: true 
      url: *datadog-url
    
    prometheus:
      enabled: true

    imagePullSecrets:
        name:

    image:
      registry: 
      repository: kraan
      tag: master

    args:
      logLevel: 0

    devmode: false

    proxy: false

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 128Mi

    tolerations: []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

gotk:
  namespace: *global-namespace
  rbac:
    enabled: true
  netpolicy:
    enabled: true

  source-controller:
    crd:
      enabled: true
    enabled: true

    name: source-controller
    datadog:
      enabled: true 
      url: *datadog-url
    
    prometheus:
      enabled: true

    image:
      registry: ghcr.io
      repository: fluxcd
      tag: v0.2.1

    imagePullSecrets:
        name:
    
    proxy: true

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 128Mi

    tolerations: []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}

  helm-controller:
    crd:
      enabled: true
    enabled: true

    name: helm-controller
    datadog:
      enabled: true 
      url: *datadog-url
    
    prometheus:
      enabled: true

    imagePullSecrets:
        name:


    image:
      registry: ghcr.io
      repository: fluxcd
      tag: v0.2.0
    
    proxy: true

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 128Mi

    tolerations: []
      # - key: "key"
      #   operator: "Equal|Exists"
      #   value: "value"
      #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

    ## Node labels for alertmanager pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector: {}

    ## Pod affinity
    ##
    affinity: {}