kraan:
  image:
    registry: 
    repository: kraan
    tag: master

  imagePullSecrets:
    name:

  args:
    logLevel: 0

gotk:
  image:
    registry: 

  imagePullSecrets:
    name:

  env:
    httpsProxy:
    noProxy: 10.0.0.0/8,172.0.0.0/8
