---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kraan-manager
rules:
- apiGroups:
  - kraan.io
  resources:
  - addonslayers
  - addonslayers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kraan-gitops-source
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  - gitrepositories/status
  - helmrepositories
  - helmrepositories/status
  verbs:
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kraan-helm-release
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  - helmreleases/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
