# permissions for end users to edit config.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-editor-role
rules:
- apiGroups:
  - kraan.io
  resources:
  - config
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kraan.io
  resources:
  - config/status
  verbs:
  - get
