# permissions for end users to view config.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-viewer-role
rules:
- apiGroups:
  - kraan.io
  resources:
  - config
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kraan.io
  resources:
  - config/status
  verbs:
  - get
