apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: gotk-system
    app.kubernetes.io/version: latest
    control-plane: controller
  name: source-controller
  namespace: gotk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: source-controller
    spec:
      containers:
      - name: manager
        args:
          - --events-addr=
          - --watch-all-namespaces=true
          - --log-level=info
          - --log-json
          - --enable-leader-election
          - --storage-path=/data
        env:
          - name: RUNTIME_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if .Values.gotk.source-controller.proxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.global.env.httpsProxy }}
          - name: NO_PROXY
            value: {{ .Values.global.env.noProxy }}
          {{- end }}
        {{- if .Values.gotk.source-controller.image.registry }}
        image: {{ .Values.gotk.source-controller.image.registry }}/{{ .Values.gotk.source-controller.image.repository | default "fluxcd" }}/source-controller:{{ .Values.gotk.source-controller.image.tag }}
        {{- else }}
        image: "ghcr.io/{{ .Values.gotk.source-controller.image.repository | default "fluxcd" }}/source-controller:{{ .Values.gotk.source-controller.image.tag }}"
        {{- end }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 8080
          name: http-prom
        readinessProbe:
          httpGet:
            path: /
            port: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
        resources:
{{ toYaml .Values.gotk.source-controller.resources | indent 10 }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.gotk.source-controller.imagePullSecrets.name }}
      imagePullSecrets:
      - name: {{ .Values.gotk.source-controller.imagePullSecrets.name }}
      {{- end }}
    {{- if .Values.gotk.source-controller.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.gotk.source-controller.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.gotk.source-controller.tolerations }}
      tolerations:
{{ toYaml .Values.gotk.source-controller.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.gotk.source-controller.affinity }}
      affinity:
{{ toYaml .Values.gotk.source-controller.affinity | indent 8 }}
    {{- end }}
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
