apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gotk-system
    app.kubernetes.io/version: latest
    control-plane: controller
  name: source-controller
  namespace: gotk-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: source-controller
  type: ClusterIP
