# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths-ignore: ["**.md"]
  pull_request:
    branches: [master]
    paths-ignore: ["**.md"]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine Tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
            export VERSION=$(cat VERSION)-dev
          else
            export VERSION=$(cat VERSION)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CHART_VERSION=$VERSION" >> $GITHUB_ENV
          echo "REPO=kraan" >> $GITHUB_ENV
          echo "using $VERSION as the release version"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.15
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup dependencies
        run: ./bin/setup.sh
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Prerelease - Lint, Test, Build, and Push
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          make clean
          make dev-build
          make docker-push-prerelease
      ### MASTER STEPS ONLY
      - name: Release - Lint, Test, Build, and Push with Helm Chart release
        if: ${{ github.event_name == 'push' }}
        run: |
          if docker pull kraan/kraan-controller:$VERSION; then
            echo "image already exists overwrite image..."
            exit 0
          fi
          make clean
          make build
          make docker-push
          # publish helm chart
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          make release
